// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3LVhIa0IxY-k3OO7_77lxUeL_bm-nRTo',
    appId: '1:100576452828:web:979fe17365a58c30209419',
    messagingSenderId: '100576452828',
    projectId: 'shop-app-6afed',
    authDomain: 'shop-app-6afed.firebaseapp.com',
    databaseURL: 'https://shop-app-6afed-default-rtdb.firebaseio.com',
    storageBucket: 'shop-app-6afed.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9J6cGRELNFIMgwUPdmFl5PbtLq8GsoDQ',
    appId: '1:100576452828:android:27638bc2723914c0209419',
    messagingSenderId: '100576452828',
    projectId: 'shop-app-6afed',
    databaseURL: 'https://shop-app-6afed-default-rtdb.firebaseio.com',
    storageBucket: 'shop-app-6afed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSleuaMG2bBMuAmqTLAr9SHClKu9cPeU8',
    appId: '1:100576452828:ios:220e4ded33ec103a209419',
    messagingSenderId: '100576452828',
    projectId: 'shop-app-6afed',
    databaseURL: 'https://shop-app-6afed-default-rtdb.firebaseio.com',
    storageBucket: 'shop-app-6afed.firebasestorage.app',
    iosBundleId: 'com.example.shopApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSleuaMG2bBMuAmqTLAr9SHClKu9cPeU8',
    appId: '1:100576452828:ios:220e4ded33ec103a209419',
    messagingSenderId: '100576452828',
    projectId: 'shop-app-6afed',
    databaseURL: 'https://shop-app-6afed-default-rtdb.firebaseio.com',
    storageBucket: 'shop-app-6afed.firebasestorage.app',
    iosBundleId: 'com.example.shopApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3LVhIa0IxY-k3OO7_77lxUeL_bm-nRTo',
    appId: '1:100576452828:web:ff90de5d5143000d209419',
    messagingSenderId: '100576452828',
    projectId: 'shop-app-6afed',
    authDomain: 'shop-app-6afed.firebaseapp.com',
    databaseURL: 'https://shop-app-6afed-default-rtdb.firebaseio.com',
    storageBucket: 'shop-app-6afed.firebasestorage.app',
  );
}
